// <auto-generated />
namespace BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTbAttendence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTbAttendence));
        
        string IMigrationMetadata.Id
        {
            get { return "202107041141119_add-Tb-Attendence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
